### ISSUE TITLE
Returned to the wrong place

### ISSUE THREAD

**Issue by christianp82** [BigNoid/skin.droid#10]
When returned to the movie view (e.g. BigIcons) after viewing a movie you aren’t returned to the same place you where before the movie (the movie you watched isn’t the one selected).

**Comment by xhaggi** [comment]
This is a XBMC specific issue and I can't reproduce it with the latest nightly.

**Comment by christianp82** [comment]
Don’t think this is an XBMC issue as it’s only when using Droid this happens (never with any other skin).
Tested on two installations of XBMC (12.2 on Windows 8 and 12.2 on OpenELEC 3.1.5).
It happens with the latest GitHub version of the skin but also with previous versions.
Two example using the BigIcons view:
I start watching the 10:th movie (next to last on the second row). When canceling (stopping) the movie the 12:th movie (first on the third row) is selected. 
Starting the 29:th movie (last on the fifth row) when done the 41:th movie (last on the seventh row) is the one selected.

**Comment by xhaggi** [comment]
Will double check this.

**Comment by christianp82** [comment]
Really old issue marked as won't fix.
