### ISSUE TITLE
Fast-forward indicator overlapping the position time

### ISSUE THREAD

**Issue by christianp82** [BigNoid/skin.droid#11]
The fast-forward indicator on the OSD (e.g. 2X>>) is overlapping the position time.
![image](https://f.cloud.github.com/assets/2353092/930908/b0555cc6-001a-11e3-915d-c769d7949e58.png)

**Comment by xhaggi** [comment]
This would be fixed if pull #7 is merged.

**Comment by christianp82** [comment]
Really old issue marked as fixed with #7.
